name: Twente Bot CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Twente Bot webhook
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        data: "Update Cloudflare DNS"
